services:
 - docker

language: python

python:
    - "3.6"

cache: pip

install: 
    - "pip install pytest"
    - "pip install pylint"

 
after_script:
# This will clone our ogranization's pylint protocols and run them over all the code within the image
    - "git clone https://github.com/AgPipeline/Organization-info.git"
    - "pylint --rcfile=Organization-info/pylint.rc common-image/*.py"
    - "pylint --rcfile=Organization-info/pylint.rc rgb-plot-base-transformer/*.py"
    - "pylint --rcfile=Organization-info/pylint.rc lidar-plot-base-transformer/*.py"