services:
 - docker

before_install:
# Build final image & name it (metadata cleaner for example)


script:
# - docker build -t common-image common-image
# - docker run common-image
 - docker build -t test-image:latest test-image
 - docker run test-image