services:
 - docker

language: python

python:
    - "3.6"

cache: pip

install: 
    - "pip install pytest"
    - "pip install pylint"

script:
# Moving file from the common-image to test-image before building
 - cp common-image/*.py test-image/
# Building the image and runnning the test within, see test-image folder for documentation there
 - docker build -t test-image:latest test-image
 - docker run test-image
 
after_script:
# This will clone our ogranization's pylint protocols and run them over all the code within the image
    - "git clone https://github.com/AgPipeline/Organization-info.git"
    - "pylint --rcfile=Organization-info/pylint.rc common-image/*.py"
    allow_failures:
        - "pylint --rcfile=Organization-info/pylint.rc common-image/*.py"
        - "pylint --rcfile=Organization-info/pylint.rc rgb-plot-base-transformer/*.py"
        - "pylint --rcfile=Organization-info/pylint.rc lidar-plot-base-transformer/*.py"