services:
 - docker

language: python

python:
    - "3.6"

cache: pip

install: 
    - "pip install pytest"
    - "pip install pylint"

matrix:
    include:
     - name: "Common-Image"
       env: TRANSFORMER_BRANCH=test-development FOLDER="common-image" USE_COMMON="" TEST_FILE="common_image_test.py"
     - name: "RGB-plot-base"
       env: TRANSFORMER_BRANCH=test-development FOLDER="rgb-plot-base-transformer" USE_COMMON="True" TEST_FILE="rgb_image_test.py"
     - name: "Lidar-plot-base"
       env: TRANSFORMER_BRANCH=test-development FOLDER="lidar-plot-base-transformer" USE_COMMON="True" TEST_FILE="lidar_image_test.py"
       
script:
    # Moving file from the common-image to test-image before building
     - cp test-image/${TEST_FILE} ${FOLDER}
    # Building the image and runnning the test within, see test-image folder for documentation there
    # - docker build -t common-image:latest common-image
     - if [ "${USE_COMMON}" == "" ] ; then pytest ${TEST_FILE} ;fi
     - if [ "${USE_COMMON}" != "" ] ; then docker build -t ${FOLDER} ${FOLDER} && python pytest ${FOLDER}/${TEST_FILE} ;fi
     - docker run ${FOLDER}

after_script:
# This will clone our ogranization's pylint protocols and run them over all the code within the image
    - "git clone https://github.com/AgPipeline/Organization-info.git"
    - "pylint --rcfile=Organization-info/pylint.rc common-image/*.py"
    - "pylint --rcfile=Organization-info/pylint.rc rgb-plot-base-transformer/*.py"
    - "pylint --rcfile=Organization-info/pylint.rc lidar-plot-base-transformer/*.py"