services:
 - docker

before_install:
# Build final image & name it (metadata cleaner for example)
 - docker build -t common-image common-image

script:
 - ls
 - ls common-image
 - ls common-image/test-files
 - docker build -t test-image test-image
 - docker run test-image