services:
 - docker

before_install:
# Build final image & name it (metadata cleaner for example)
 - docker build -t common-image common-image

script:
 - docker build -ft testing_dockerfile testing-image
 - docker run testing-image