services:
 - docker

script:
 - cp common-image/*.py test-image/
 - git clone https://github.com/AgPipeline/Organization-info.git
 - cp Organization-info/pylint.rc test-image/
# - pylint --rcfile=Organization-info/pylint.rc test-image/*.py
 - docker build -t test-image:latest test-image
 - docker run test-image